baseURL = 'https://420blazeit.today/'
languageCode = 'en-us'
title = 'Angerblog'
theme = "hugo-book"

[[menu.main]]
name = "Docs folder"
identifier = "docs"
url = "/content/docs/"

[[menu.main]]
name = "Brot & Co"
parent = "docs"
identifier = "breads"
url = "/content/docs/bread/"